Possibility to specify an update check interval for the web worker.
maxence-charriere/go-app pull request #705
Opened 2022-03-22 15:02 UTC by oderwat

With this change, it is possible to specify an interval at which the server is checked for updates. Set this to one hour or just some seconds (while development) to have the web worker update itself and trigger the `OnAppUpdate` handler without manually reloading the page or the need for the user to browse to another URL. This combined with a UX dialog that tells the user that an update is pending should solve the problem with long-running apps that only use internal routes and API calls without ever loading another page from the server itself.

2022-03-24 05:08 UTC, maxence-charriere requested changes
This seems to be a pretty useful change. Thanks for writing this PR.

Just a few things that could be polished and I'll gladly merge this.

2022-03-24 05:08 UTC, maxence-charriere commented on pkg/app/http.go
> +			UpdateInterval: strconv.Itoa(h.UpdateInterval),
With the auto-update interval set as a duration here would have to be changed to:
```go
AutoUpdateInterval: AutoUpdateInterval.Milliseconds(),
```

2022-03-24 05:08 UTC, maxence-charriere commented on pkg/app/http.go
> +			UpdateInterval string
From https://developer.mozilla.org/en-US/docs/Web/API/setInterval, a delay is a number in milliseconds.

Here can use:
```go
AutoUpdateInterval int64
```

2022-03-24 05:08 UTC, maxence-charriere commented on pkg/app/gen/app.js
> +const updateInterval = {{.UpdateInterval}};
Would be good to have this named `autoUpdateInterval`:

```js
const autoUpdateInterval = {{.AutoUpdateInterval}};
```

2022-03-24 13:02 UTC, oderwat commented
I made the change you proposed. Very nice!

2022-03-26 09:05 UTC, maxence-charriere approved these changes

2022-03-26 09:05 UTC, merged